# Generated by Django 2.2.7 on 2019-11-30 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20191129_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dresses',
            old_name='user',
            new_name='name',
        ),
    ]
