# Generated by Django 2.2.7 on 2019-12-02 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20191129_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dresses',
            old_name='name',
            new_name='user',
        ),
    ]
