# Generated by Django 2.2.7 on 2019-12-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20191201_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hips',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='hips'),
        ),
        migrations.AddField(
            model_name='profile',
            name='thighs',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='thighs'),
        ),
        migrations.AddField(
            model_name='profile',
            name='waist',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='waist'),
        ),
    ]
