# Generated by Django 2.2.7 on 2019-12-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20191203_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='dresses',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='dress_pics'),
        ),
        migrations.AddField(
            model_name='dresses',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
