# Generated by Django 2.2.7 on 2019-12-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_dresses_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dresses',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='dresses',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
